import type { Metadata } from "next";
import { Caveat,Inter } from "next/font/google";
import "./globals.css";

const caveat = Caveat({
  subsets: ["latin"],
  variable: "--font-caveat",
  display:"swap"
});

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display:"swap"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${caveat.variable} ${inter.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
